import Footer from "@/components/Footer/footer"
import AuthProvider from "../providers/AuthProvider"
import "../globals.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body style={{height:"100vh",display:"flex",flexDirection:"column"}}
        // style={{
        //   height: "100vh",
        //   display: "grid",
        //   gridTemplateRows: "auto 1fr auto",
        //   alignItems: "center",
        // }}
        // className="text-center text-bg-dark auth-pages"
      >
      <AuthProvider>
        {children}
        </AuthProvider>
        <Footer style={{marginTop:"auto"}}/>
        </body>
    </html>
  )
}
