
import { Inter } from "next/font/google";
import "../globals.css";
import AuthProvider from "../providers/AuthProvider";
import { CartProvider } from "@/app/context/cartcontext";
import { ThemeProvider } from "@/app/context/ThemeContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className={inter.className}>
        
    <AuthProvider>
      <ThemeProvider>
      <CartProvider>
        {children}
        </CartProvider>
        </ThemeProvider>
        </AuthProvider>
        
        </body>
    </html>
  );
}
